import { test, expect } from '@playwright/test';
test('test', async ({ page }) => {
  test.setTimeout(700000);
  await page.goto('https://www.ryanair.com/pt/pt');
  await page.getByRole('button', { name: 'Sim, concordo' }).click();
  await page.getByPlaceholder('Partida').click();
  await page.getByRole('button', { name: 'Porto' }).click();
  await page.getByRole('button', { name: 'Marrocos' }).click();
  await page.getByRole('button', { name: 'Marraquexe' }).click();
  await page.getByText('1', { exact: true }).nth(1).click();
  await page.getByText('3', { exact: true }).nth(1).click();
  await page.getByLabel('Feito').click();
  await page.getByLabel('Pesquisar').click();
  await page.locator('flight-card-summary').filter({ hasText: '1 lugares restantes com este' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Selecionar' }).click();
  await page.getByRole('columnheader', { name: 'Image that represents standard fare Basic Viaja sem peso Continuar para € 80 ,' }).locator('div').nth(4).click();
  await page.getByRole('button', { name: 'Continuar com Basic' }).click();
  await page.getByRole('button', { name: 'Iniciar sessão mais tarde' }).click();
  await page.getByRole('button', { name: '-', exact: true }).click();
  await page.getByRole('button', { name: 'Sr.', exact: true }).click();
  await page.getByLabel('Nome próprio').click();
  await page.getByLabel('Nome próprio').fill('David');
  await page.getByLabel('Apelido').click();
  await page.getByLabel('Apelido').fill('Vilas Boas');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.locator('bags-small-bag-pax-control label').click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Adicionar lugares recomendados' }).click();
  await page.getByRole('button', { name: 'Não, obrigado' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await expect(page.locator('ry-header-modal')).toContainText('Iniciar sessão para continuar');
});
